# platform :ios, '9.0'

target 'Runner' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
  
    # Pods for Runner
    pod 'GoogleMaps'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
  end